import type { Feature, FeatureCollection, Geometry, Point } from "geojson";
import type { EnvironmentalArea, Project, PublicComment, Zone } from "../types";

export const mobilityCorridors: Feature[] = [
  {
    type: "Feature",
    properties: {
      id: "MOB-001",
      name: "East-West public transport priority spine",
      corridorType: "Bus and tram priority",
      status: "Concept",
    },
    geometry: {
      type: "LineString",
      coordinates: [[13.398, 52.516], [13.424, 52.518], [13.454, 52.515], [13.475, 52.51]],
    },
  },
  {
    type: "Feature",
    properties: {
      id: "MOB-002",
      name: "North-South cycling priority route",
      corridorType: "Protected cycle route",
      status: "Feasibility",
    },
    geometry: {
      type: "LineString",
      coordinates: [[13.386, 52.55], [13.388, 52.535], [13.392, 52.518], [13.399, 52.501]],
    },
  },
];

export const projectPointFeature = (project: Project): Feature<Point> => ({
  type: "Feature",
  properties: {
    id: project.id,
    name: project.name,
    district: project.district,
    status: project.status,
    riskLevel: project.riskLevel,
    kind: "project",
  },
  geometry: {
    type: "Point",
    coordinates: [project.location[1], project.location[0]],
  },
});

export const commentPointFeature = (comment: PublicComment): Feature<Point> => ({
  type: "Feature",
  properties: {
    id: comment.id,
    name: comment.anonymous ? "Anonymous" : comment.name,
    category: comment.category,
    sentiment: comment.sentiment,
    status: comment.status,
    kind: "comment",
  },
  geometry: {
    type: "Point",
    coordinates: [comment.location[1], comment.location[0]],
  },
});

export const buildExportGeoJson = (
  zones: Zone[],
  projects: Project[],
  environmentalAreas: EnvironmentalArea[],
  publicComments: PublicComment[],
): FeatureCollection<Geometry> => {
  const features: Feature<Geometry>[] = [
    ...zones.map((zone) => ({
      ...zone.geometry,
      properties: { ...zone.geometry.properties, name: zone.name, type: zone.type, source: "zones" },
    })),
    ...projects.map(projectPointFeature),
    ...projects.flatMap((project) => (project.geometry ? [{ ...project.geometry, properties: { ...project.geometry.properties, name: project.name, source: "projects" } }] : [])),
    ...environmentalAreas.map((area) => ({
      ...area.geometry,
      properties: { ...area.geometry.properties, name: area.name, type: area.type, score: area.score, source: "environment" },
    })),
    ...publicComments.map(commentPointFeature),
    ...mobilityCorridors,
  ];

  return {
    type: "FeatureCollection",
    features,
  };
};

export const downloadGeoJson = (collection: FeatureCollection<Geometry>, filename: string) => {
  const blob = new Blob([JSON.stringify(collection, null, 2)], {
    type: "application/geo+json",
  });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
};

// This helper is the future seam for Azure Blob Storage or QGIS export APIs.
export const describeQgisExport = () =>
  "GeoJSON can be imported into QGIS today. In Azure, this export would be generated by Functions and stored in Blob Storage with signed download links.";
